import type {
  WarningSignal,
  RiskEvent,
  PostLoanCheck,
  WarningRule,
  WarningStatistics,
  EnterpriseRiskProfile,
} from '../types';

// 模拟预警信号
export const mockWarningSignals: WarningSignal[] = [
  {
    id: 'warning-001',
    enterpriseId: 'ent-001',
    enterpriseName: '浙江华创科技有限公司',
    type: 'external',
    level: 'high',
    status: 'active',
    title: '企业涉及重大诉讼',
    description: '企业作为被告涉及一起买卖合同纠纷案件，涉案金额1200万元，占企业净资产的15%。',
    source: '中国裁判文书网',
    occurredAt: '2024-03-15',
    detectedAt: '2024-03-16 08:30:00',
    assignee: '张三',
    impact: '可能导致企业资金链紧张，影响还款能力',
    suggestion: '建议立即联系企业了解诉讼详情，评估对还款能力的影响',
    relatedLoan: {
      id: 'loan-001',
      amount: 50000000,
      type: '流动资金贷款',
    },
  },
  {
    id: 'warning-002',
    enterpriseId: 'ent-002',
    enterpriseName: '杭州智联物联网科技有限公司',
    type: 'financial',
    level: 'medium',
    status: 'processing',
    title: '应收账款周转率下降',
    description: '企业应收账款周转率从上季度的5.2下降至本季度的3.1，降幅达40%，显示回款效率明显降低。',
    source: '财务数据监控',
    occurredAt: '2024-03-10',
    detectedAt: '2024-03-12 10:00:00',
    assignee: '李四',
    impact: '可能影响企业短期偿债能力',
    suggestion: '建议核实主要客户付款情况，关注是否存在坏账风险',
    relatedLoan: {
      id: 'loan-002',
      amount: 30000000,
      type: '流动资金贷款',
    },
  },
  {
    id: 'warning-003',
    enterpriseId: 'ent-003',
    enterpriseName: '宁波海天机械制造有限公司',
    type: 'behavior',
    level: 'high',
    status: 'active',
    title: '实际控制人变更',
    description: '企业实际控制人由王某某变更为李某某，股权结构发生重大调整。',
    source: '工商变更监控',
    occurredAt: '2024-03-08',
    detectedAt: '2024-03-09 09:15:00',
    impact: '实际控制人变更可能影响企业经营策略和还款意愿',
    suggestion: '建议尽快约谈新实际控制人，了解经营规划',
    relatedLoan: {
      id: 'loan-003',
      amount: 80000000,
      type: '项目贷款',
    },
  },
  {
    id: 'warning-004',
    enterpriseId: 'ent-004',
    enterpriseName: '温州嘉信贸易集团有限公司',
    type: 'internal',
    level: 'low',
    status: 'resolved',
    title: '贷款用途偏离预警',
    description: '企业贷款资金使用与批复用途存在轻微偏离，部分资金用于补充流动资金而非采购原材料。',
    source: '资金流向监控',
    occurredAt: '2024-03-05',
    detectedAt: '2024-03-06 14:20:00',
    assignee: '王五',
    impact: '贷款用途合规性风险',
    suggestion: '已要求企业说明情况并补充相关材料',
    relatedLoan: {
      id: 'loan-004',
      amount: 20000000,
      type: '流动资金贷款',
    },
  },
  {
    id: 'warning-005',
    enterpriseId: 'ent-005',
    enterpriseName: '嘉兴新材科技股份有限公司',
    type: 'external',
    level: 'medium',
    status: 'active',
    title: '行业政策风险',
    description: '环保部门发布新规，对企业所属行业提出更严格的环保要求，可能增加企业运营成本。',
    source: '政策监控',
    occurredAt: '2024-03-01',
    detectedAt: '2024-03-02 11:00:00',
    impact: '可能影响企业盈利能力',
    suggestion: '建议评估企业环保合规情况及应对措施',
    relatedLoan: {
      id: 'loan-005',
      amount: 45000000,
      type: '项目贷款',
    },
  },
  {
    id: 'warning-006',
    enterpriseId: 'ent-006',
    enterpriseName: '绍兴纺织印染有限公司',
    type: 'financial',
    level: 'low',
    status: 'ignored',
    title: '毛利率小幅下滑',
    description: '企业毛利率从上季度的28%下降至本季度的25%，降幅在正常波动范围内。',
    source: '财务数据监控',
    occurredAt: '2024-02-28',
    detectedAt: '2024-03-01 09:00:00',
    impact: '盈利能力轻微下降',
    suggestion: '持续关注后续季度数据',
    relatedLoan: {
      id: 'loan-006',
      amount: 15000000,
      type: '流动资金贷款',
    },
  },
];

// 模拟风险事件
export const mockRiskEvents: RiskEvent[] = [
  {
    id: 'event-001',
    signalId: 'warning-001',
    enterpriseName: '浙江华创科技有限公司',
    title: '重大诉讼风险处置',
    description: '企业涉及重大诉讼案件，需要持续跟踪处置',
    level: 'high',
    status: 'processing',
    timeline: [
      {
        id: 'tl-001',
        timestamp: '2024-03-16 08:30:00',
        action: '预警信号触发',
        operator: '系统',
        status: 'active',
      },
      {
        id: 'tl-002',
        timestamp: '2024-03-16 09:00:00',
        action: '分配处理人员',
        operator: '系统',
        remark: '分配给客户经理张三',
        status: 'active',
      },
      {
        id: 'tl-003',
        timestamp: '2024-03-16 14:00:00',
        action: '联系企业了解情况',
        operator: '张三',
        remark: '企业表示案件正在应诉中，预计3个月内判决',
        status: 'processing',
      },
      {
        id: 'tl-004',
        timestamp: '2024-03-18 10:00:00',
        action: '风险评级调整',
        operator: '张三',
        remark: '风险等级由正常调整为关注',
        status: 'processing',
      },
    ],
    createdAt: '2024-03-16 08:30:00',
    updatedAt: '2024-03-18 10:00:00',
    handler: '张三',
  },
  {
    id: 'event-002',
    signalId: 'warning-003',
    enterpriseName: '宁波海天机械制造有限公司',
    title: '实际控制人变更处置',
    description: '企业实际控制人变更，需要评估影响',
    level: 'high',
    status: 'active',
    timeline: [
      {
        id: 'tl-005',
        timestamp: '2024-03-09 09:15:00',
        action: '预警信号触发',
        operator: '系统',
        status: 'active',
      },
      {
        id: 'tl-006',
        timestamp: '2024-03-09 10:00:00',
        action: '发起专项检查',
        operator: '系统',
        remark: '触发贷后专项检查任务',
        status: 'active',
      },
    ],
    createdAt: '2024-03-09 09:15:00',
    updatedAt: '2024-03-09 10:00:00',
  },
];

// 模拟贷后检查任务
export const mockPostLoanChecks: PostLoanCheck[] = [
  {
    id: 'check-001',
    enterpriseId: 'ent-001',
    enterpriseName: '浙江华创科技有限公司',
    type: 'triggered',
    status: 'in_progress',
    scheduledDate: '2024-03-20',
    assignee: '张三',
    items: [
      {
        id: 'item-001',
        category: '经营状况',
        content: '核实企业当前经营是否正常',
        result: 'pass',
        remark: '企业正常经营，订单充足',
      },
      {
        id: 'item-002',
        category: '财务状况',
        content: '核实最新财务数据',
        result: 'pending',
      },
      {
        id: 'item-003',
        category: '诉讼情况',
        content: '了解诉讼案件详情及进展',
        result: 'pending',
      },
      {
        id: 'item-004',
        category: '还款能力',
        content: '评估对还款能力的影响',
        result: 'pending',
      },
    ],
  },
  {
    id: 'check-002',
    enterpriseId: 'ent-002',
    enterpriseName: '杭州智联物联网科技有限公司',
    type: 'regular',
    status: 'completed',
    scheduledDate: '2024-03-15',
    completedDate: '2024-03-14',
    assignee: '李四',
    items: [
      {
        id: 'item-005',
        category: '经营状况',
        content: '核实企业当前经营是否正常',
        result: 'pass',
      },
      {
        id: 'item-006',
        category: '财务状况',
        content: '核实最新财务数据',
        result: 'pass',
      },
      {
        id: 'item-007',
        category: '担保状况',
        content: '核实担保物状况',
        result: 'pass',
        remark: '抵押物价值稳定',
      },
    ],
    summary: '企业经营正常，财务指标良好，担保物价值稳定',
    conclusion: 'normal',
  },
  {
    id: 'check-003',
    enterpriseId: 'ent-003',
    enterpriseName: '宁波海天机械制造有限公司',
    type: 'triggered',
    status: 'pending',
    scheduledDate: '2024-03-22',
    assignee: '王五',
    items: [
      {
        id: 'item-008',
        category: '股权变更',
        content: '核实实际控制人变更原因',
        result: 'pending',
      },
      {
        id: 'item-009',
        category: '经营规划',
        content: '了解新实际控制人经营规划',
        result: 'pending',
      },
      {
        id: 'item-010',
        category: '还款意愿',
        content: '评估新实际控制人还款意愿',
        result: 'pending',
      },
    ],
  },
  {
    id: 'check-004',
    enterpriseId: 'ent-007',
    enterpriseName: '台州精密模具有限公司',
    type: 'regular',
    status: 'overdue',
    scheduledDate: '2024-03-10',
    assignee: '赵六',
    items: [
      {
        id: 'item-011',
        category: '经营状况',
        content: '核实企业当前经营是否正常',
        result: 'pending',
      },
      {
        id: 'item-012',
        category: '财务状况',
        content: '核实最新财务数据',
        result: 'pending',
      },
    ],
  },
  {
    id: 'check-005',
    enterpriseId: 'ent-008',
    enterpriseName: '金华机械设备有限公司',
    type: 'special',
    status: 'pending',
    scheduledDate: '2024-03-25',
    assignee: '张三',
    items: [
      {
        id: 'item-013',
        category: '专项核查',
        content: '核实环保整改情况',
        result: 'pending',
      },
      {
        id: 'item-014',
        category: '经营影响',
        content: '评估环保政策对经营的影响',
        result: 'pending',
      },
    ],
  },
];

// 模拟预警规则
export const mockWarningRules: WarningRule[] = [
  {
    id: 'rule-001',
    name: '重大诉讼预警',
    category: 'external',
    description: '当企业涉及重大诉讼案件（涉案金额超过净资产的10%）时触发预警',
    conditions: [
      { id: 'cond-001', field: 'lawsuit_amount_ratio', operator: 'gte', value: 10, unit: '%' },
    ],
    level: 'high',
    enabled: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-03-01',
  },
  {
    id: 'rule-002',
    name: '实际控制人变更预警',
    category: 'internal',
    description: '当企业实际控制人发生变更时触发预警',
    conditions: [
      { id: 'cond-002', field: 'actual_controller', operator: 'changed', value: 'true' },
    ],
    level: 'high',
    enabled: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'rule-003',
    name: '应收账款周转率下降预警',
    category: 'financial',
    description: '当应收账款周转率环比下降超过30%时触发预警',
    conditions: [
      { id: 'cond-003', field: 'receivable_turnover_change', operator: 'lte', value: -30, unit: '%' },
    ],
    level: 'medium',
    enabled: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-02-15',
  },
  {
    id: 'rule-004',
    name: '贷款用途偏离预警',
    category: 'behavior',
    description: '当贷款资金流向与批复用途不一致时触发预警',
    conditions: [
      { id: 'cond-004', field: 'fund_usage_match', operator: 'eq', value: 'false' },
    ],
    level: 'low',
    enabled: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'rule-005',
    name: '毛利率下降预警',
    category: 'financial',
    description: '当毛利率环比下降超过10%时触发预警',
    conditions: [
      { id: 'cond-005', field: 'gross_margin_change', operator: 'lte', value: -10, unit: '%' },
    ],
    level: 'low',
    enabled: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'rule-006',
    name: '被执行人预警',
    category: 'external',
    description: '当企业被列为被执行人时触发预警',
    conditions: [
      { id: 'cond-006', field: 'is_enforced', operator: 'eq', value: 'true' },
    ],
    level: 'high',
    enabled: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
];

// 模拟预警统计
export const mockWarningStatistics: WarningStatistics = {
  total: 6,
  high: 2,
  medium: 2,
  low: 2,
  active: 3,
  processing: 1,
  resolved: 1,
  trend: [
    { date: '2024-03-01', count: 2 },
    { date: '2024-03-05', count: 3 },
    { date: '2024-03-10', count: 5 },
    { date: '2024-03-15', count: 4 },
    { date: '2024-03-20', count: 6 },
  ],
};

// 模拟企业风险画像
export const mockEnterpriseRiskProfiles: EnterpriseRiskProfile[] = [
  {
    enterpriseId: 'ent-001',
    enterpriseName: '浙江华创科技有限公司',
    loanAmount: 50000000,
    loanBalance: 48000000,
    riskScore: 72,
    warningCount: 1,
    lastCheckDate: '2024-03-18',
    nextCheckDate: '2024-06-18',
    riskFactors: [
      { id: 'rf-001', name: '诉讼风险', category: '法律', score: 85, trend: 'up', description: '涉及重大诉讼案件' },
      { id: 'rf-002', name: '经营风险', category: '经营', score: 45, trend: 'stable', description: '经营状况正常' },
      { id: 'rf-003', name: '财务风险', category: '财务', score: 55, trend: 'stable', description: '财务指标基本正常' },
    ],
  },
  {
    enterpriseId: 'ent-002',
    enterpriseName: '杭州智联物联网科技有限公司',
    loanAmount: 30000000,
    loanBalance: 28000000,
    riskScore: 58,
    warningCount: 1,
    lastCheckDate: '2024-03-14',
    nextCheckDate: '2024-06-14',
    riskFactors: [
      { id: 'rf-004', name: '回款风险', category: '财务', score: 70, trend: 'up', description: '应收账款周转率下降' },
      { id: 'rf-005', name: '经营风险', category: '经营', score: 40, trend: 'stable', description: '经营状况良好' },
    ],
  },
  {
    enterpriseId: 'ent-003',
    enterpriseName: '宁波海天机械制造有限公司',
    loanAmount: 80000000,
    loanBalance: 75000000,
    riskScore: 68,
    warningCount: 1,
    lastCheckDate: '2024-03-01',
    nextCheckDate: '2024-03-22',
    riskFactors: [
      { id: 'rf-006', name: '控制人风险', category: '管理', score: 80, trend: 'up', description: '实际控制人变更' },
      { id: 'rf-007', name: '经营风险', category: '经营', score: 50, trend: 'stable', description: '经营状况待核实' },
    ],
  },
];
